server:
  port: 8099


account:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: transaction-manager
    password: xxxxx


jms-broker:
  url: tcp://localhost:61616
  username: email
  password: xxxxxx
